<#assign shipment = input.shipment[0]>

{
"transportInstructionId":"${input.transportInstructionId}",
"shipment":[
{

"primaryId":"${shipment.shipmentId}",
"customerCode":"${shipment.customerNumber}",
"shipFrom":{
"primaryId":"${shipment.shipTo.toShipmentId}",
"organisationName":"FAKE_DATA",
"isResidentialAddress":false,
"contact":[
{
"personName":"fake_data",
"communicationChannel":[
{
"communicationChannelCode":"EMAIL",
"communicationValue":"fake_data",
"communicationChannelName":"fake_data"
}
]
}
],
"address":{
"streetAddressOne":"fake_data",
"streetAddressTwo":"fake_data",
"streetAddressThree":"fake_data",
"city":"fake_data",
"countryCode":"fake_data",
"name":"fake_data",
"state":"fake_data",
"postalCode":"fake_data",
"geographicalCoordinates":{
"latitude":"fake_data",
"longitude":"fake_data"
}
}
},
"shipTo":{
"primaryId":"fake_data",
"organisationName":"fake_data",
"isResidentialAddress":true,
"contact":[
{
"personName":"fake_data",
"communicationChannel":[
{
"communicationChannelCode":"EMAIL",
"communicationValue":"fake_data",
"communicationChannelName":"fake_data"
}
]
}
],
"address":{
"streetAddressOne":"fake_data",
"streetAddressTwo":"fake_data",
"streetAddressThree":"fake_data",
"city":"fake_data",
"countryCode":"fake_data",
"name":"fake_data",
"state":"fake_data",
"postalCode":"fake_data",
"geographicalCoordinates":{
"latitude":"fake_data",
"longitude":"fake_data"
}
}
},
"plannedDespatch":{
"logisticEventPeriod":{
"beginDate":"fake_data",
"beginTime":"fake_data",
"endDate":"fake_data",
"endTime":"fake_data"
}
},
"plannedDelivery":{
"logisticEventPeriod":{
"beginDate":"fake_data",
"beginTime":"fake_data",
"endDate":"fake_data",
"endTime":"fake_data"
}
},
"note":[
{
"lineNumber":"fake_data",
"isPrintable":false,
"text":{
"languageCode":"fake_data",
"value":"fake_data"
},
"type":"fake_data"
}
]
}
],
"billTo":{
"primaryId":"fake_data",
"name":"fake_data"
}
}